In [ ]:
import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error

from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestRegressor

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = '/content/drive/My Drive/yearIV/raw_storm_data.csv'

In [ ]:
df = pd.read_csv(file_path)

<ipython-input-4-47c250c455f0>:1: DtypeWarning: Columns (16,26,28,29,34,35,37,39,40,42,43,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [ ]:
df.dtypes

BEGIN_YEARMONTH         int64
BEGIN_DAY               int64
BEGIN_TIME              int64
END_YEARMONTH           int64
END_DAY                 int64
END_TIME                int64
EPISODE_ID            float64
EVENT_ID                int64
STATE                  object
STATE_FIPS            float64
YEAR                    int64
MONTH_NAME             object
EVENT_TYPE             object
CZ_TYPE                object
CZ_FIPS                 int64
CZ_NAME                object
WFO                    object
BEGIN_DATE_TIME        object
CZ_TIMEZONE            object
END_DATE_TIME          object
INJURIES_DIRECT         int64
INJURIES_INDIRECT       int64
DEATHS_DIRECT           int64
DEATHS_INDIRECT         int64
DAMAGE_PROPERTY       float64
DAMAGE_CROPS          float64
SOURCE                 object
MAGNITUDE             float64
MAGNITUDE_TYPE         object
FLOOD_CAUSE            object
CATEGORY              float64
TOR_F_SCALE            object
TOR_LENGTH            float64
TOR_WIDTH             float64
TOR_OTHER_WFO          object
TOR_OTHER_CZ_STATE     object
TOR_OTHER_CZ_FIPS     float64
TOR_OTHER_CZ_NAME      object
BEGIN_RANGE           float64
BEGIN_AZIMUTH          object
BEGIN_LOCATION         object
END_RANGE             float64
END_AZIMUTH            object
END_LOCATION           object
BEGIN_LAT             float64
BEGIN_LON             float64
END_LAT               float64
END_LON               float64
EPISODE_NARRATIVE      object
EVENT_NARRATIVE        object
DATA_SOURCE            object
NET_DAMAGE            float64
BEGIN                  object
END                    object
DURATION              float64
DURATION_HOURS        float64
DURATION_MINS         float64
dtype: object

In [ ]:
null_count = df.isnull().sum()
null_count

BEGIN_YEARMONTH             0
BEGIN_DAY                   0
BEGIN_TIME                  0
END_YEARMONTH               0
END_DAY                     0
END_TIME                    0
EPISODE_ID             156921
EVENT_ID                    0
STATE                       1
STATE_FIPS                  1
YEAR                        0
MONTH_NAME                  0
EVENT_TYPE                  0
CZ_TYPE                     0
CZ_FIPS                     0
CZ_NAME                    42
WFO                     59044
BEGIN_DATE_TIME             0
CZ_TIMEZONE                 0
END_DATE_TIME               0
INJURIES_DIRECT             0
INJURIES_INDIRECT           0
DEATHS_DIRECT               0
DEATHS_INDIRECT             0
DAMAGE_PROPERTY             0
DAMAGE_CROPS                0
SOURCE                 270535
MAGNITUDE              828279
MAGNITUDE_TYPE        1349312
FLOOD_CAUSE           1744401
CATEGORY              1861969
TOR_F_SCALE           1805920
TOR_LENGTH            1664592
TOR_WIDTH             1664592
TOR_OTHER_WFO         1859101
TOR_OTHER_CZ_STATE    1859101
TOR_OTHER_CZ_FIPS     1859101
TOR_OTHER_CZ_NAME     1859101
BEGIN_RANGE            864676
BEGIN_AZIMUTH         1008069
BEGIN_LOCATION         757164
END_RANGE              864951
END_AZIMUTH           1021047
END_LOCATION           796534
BEGIN_LAT              748491
BEGIN_LON              748498
END_LAT                858120
END_LON                858127
EPISODE_NARRATIVE      403781
EVENT_NARRATIVE        811465
DATA_SOURCE                 9
NET_DAMAGE                  0
BEGIN                       0
END                         0
DURATION                    0
DURATION_HOURS              0
DURATION_MINS               0
dtype: int64

In [ ]:
df = df.drop(['BEGIN_YEARMONTH', 'BEGIN_DAY', 'BEGIN_TIME', 'END_YEARMONTH', 'END_DAY', 'END_TIME', 'DATA_SOURCE', 'DURATION',
              'DURATION_MINS', 'WFO', 'SOURCE', 'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY', 'YEAR', 'MONTH_NAME',
              'TOR_OTHER_WFO', 'TOR_OTHER_CZ_STATE', 'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE', 'BEGIN_AZIMUTH',
              'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH', 'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON'], axis=1)

In [ ]:
df.head()

,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,BEGIN_DATE_TIME,CZ_TIMEZONE,...,DAMAGE_CROPS,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,EPISODE_NARRATIVE,EVENT_NARRATIVE,NET_DAMAGE,BEGIN,END,DURATION_HOURS
0,190907.0,1180619,OKLAHOMA,40.0,Hail,C,65,JACKSON,23-MAY-24 19:47:00,CST-6,...,0.0,NaN,NaN,NaN,Two primary rounds of severe convection occurr...,MPing report.,0.0,2024-05-23 19:47:00,2024-05-23 19:47:00,0.000000
1,197838.0,1223377,OREGON,41.0,Heavy Snow,Z,509,EAST SLOPES OF THE OREGON CASCADES,16-NOV-24 02:30:00,PST-8,...,0.0,NaN,NaN,NaN,A series of cold fronts the weekend of Nov. 16...,The Hog Pass SNOTEL reported an estimated 12 i...,0.0,2024-11-16 02:30:00,2024-11-18 14:21:00,59.850000
2,190905.0,1184919,OKLAHOMA,40.0,Tornado,C,39,CUSTER,19-MAY-24 18:39:00,CST-6,...,0.0,EF1,6.7,400.0,Significant severe weather occurred across por...,While the large multiple-vortex tornado was ap...,150000.0,2024-05-19 18:39:00,2024-05-19 19:02:00,0.383333
3,190907.0,1180805,OKLAHOMA,40.0,Thunderstorm Wind,C,51,GRADY,23-MAY-24 21:55:00,CST-6,...,0.0,NaN,NaN,NaN,Two primary rounds of severe convection occurr...,Relayed image showing a portable outbuilding b...,10000.0,2024-05-23 21:55:00,2024-05-23 21:55:00,0.000000
4,197326.0,1220680,NEW YORK,36.0,Winter Weather,Z,67,ORANGE,22-NOV-24 04:00:00,EST-5,...,0.0,NaN,NaN,NaN,An occluded low pressure system brought heavy ...,A trained spotter reported 10.0 inches of wet ...,0.0,2024-11-22 04:00:00,2024-11-22 11:00:00,7.000000

In [ ]:
df['BEGIN'] = pd.to_datetime(df['BEGIN'], format='%Y-%m-%d %H:%M:%S')

In [ ]:
df['END'] = pd.to_datetime(df['END'], format='%Y-%m-%d %H:%M:%S')

In [ ]:
df['duration_hours'] = (df['END'] - df['BEGIN']).dt.total_seconds() / 3600

In [ ]:
df[['BEGIN', 'END', 'DURATION_HOURS', 'duration_hours']][abs(df['DURATION_HOURS'] - df['duration_hours']) > 0.01]

Empty DataFrame
Columns: [BEGIN, END, DURATION_HOURS, duration_hours]
Index: []

In [ ]:
df = df.drop('DURATION_HOURS', axis=1)

In [ ]:
df.head()

,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,BEGIN_DATE_TIME,CZ_TIMEZONE,...,DAMAGE_CROPS,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,EPISODE_NARRATIVE,EVENT_NARRATIVE,NET_DAMAGE,BEGIN,END,duration_hours
0,190907.0,1180619,OKLAHOMA,40.0,Hail,C,65,JACKSON,23-MAY-24 19:47:00,CST-6,...,0.0,NaN,NaN,NaN,Two primary rounds of severe convection occurr...,MPing report.,0.0,2024-05-23 19:47:00,2024-05-23 19:47:00,0.000000
1,197838.0,1223377,OREGON,41.0,Heavy Snow,Z,509,EAST SLOPES OF THE OREGON CASCADES,16-NOV-24 02:30:00,PST-8,...,0.0,NaN,NaN,NaN,A series of cold fronts the weekend of Nov. 16...,The Hog Pass SNOTEL reported an estimated 12 i...,0.0,2024-11-16 02:30:00,2024-11-18 14:21:00,59.850000
2,190905.0,1184919,OKLAHOMA,40.0,Tornado,C,39,CUSTER,19-MAY-24 18:39:00,CST-6,...,0.0,EF1,6.7,400.0,Significant severe weather occurred across por...,While the large multiple-vortex tornado was ap...,150000.0,2024-05-19 18:39:00,2024-05-19 19:02:00,0.383333
3,190907.0,1180805,OKLAHOMA,40.0,Thunderstorm Wind,C,51,GRADY,23-MAY-24 21:55:00,CST-6,...,0.0,NaN,NaN,NaN,Two primary rounds of severe convection occurr...,Relayed image showing a portable outbuilding b...,10000.0,2024-05-23 21:55:00,2024-05-23 21:55:00,0.000000
4,197326.0,1220680,NEW YORK,36.0,Winter Weather,Z,67,ORANGE,22-NOV-24 04:00:00,EST-5,...,0.0,NaN,NaN,NaN,An occluded low pressure system brought heavy ...,A trained spotter reported 10.0 inches of wet ...,0.0,2024-11-22 04:00:00,2024-11-22 11:00:00,7.000000

In [ ]:
df = df.rename(columns={'duration_hours': 'DURATION_HOURS'})

In [ ]:
storm_ratings_bool_series = pd.notnull(df['TOR_F_SCALE'])

In [ ]:
df_subset = df[storm_ratings_bool_series]

In [ ]:
df_subset.head()

,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,BEGIN_DATE_TIME,CZ_TIMEZONE,...,DAMAGE_CROPS,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,EPISODE_NARRATIVE,EVENT_NARRATIVE,NET_DAMAGE,BEGIN,END,DURATION_HOURS
2,190905.0,1184919,OKLAHOMA,40.0,Tornado,C,39,CUSTER,19-MAY-24 18:39:00,CST-6,...,0.0,EF1,6.70,400.0,Significant severe weather occurred across por...,While the large multiple-vortex tornado was ap...,150000.0,2024-05-19 18:39:00,2024-05-19 19:02:00,0.383333
18,196653.0,1216653,IOWA,19.0,Tornado,C,51,DAVIS,05-NOV-24 11:01:00,CST-6,...,0.0,EF0,0.32,50.0,A brief tornado occurred with a shower in Davi...,A brief tornado occurred south of Floris from ...,120000.0,2024-11-05 11:01:00,2024-11-05 11:02:00,0.016667
105,188190.0,1155977,ILLINOIS,17.0,Tornado,C,31,COOK,27-FEB-24 19:32:00,CST-6,...,0.0,EF1,2.58,110.0,"Following summer-like, record warmth, severe t...",This tornado touched down in the area near Del...,0.0,2024-02-27 19:32:00,2024-02-27 19:35:00,0.050000
106,188190.0,1155978,ILLINOIS,17.0,Tornado,C,31,COOK,27-FEB-24 19:34:00,CST-6,...,0.0,EF1,2.45,160.0,"Following summer-like, record warmth, severe t...",This tornado formed near Studio Drive in South...,0.0,2024-02-27 19:34:00,2024-02-27 19:37:00,0.050000
111,188190.0,1155954,ILLINOIS,17.0,Tornado,C,103,LEE,27-FEB-24 18:15:00,CST-6,...,0.0,EF0,0.05,10.0,"Following summer-like, record warmth, severe t...","A brief tornado, which was sighted by storm ch...",0.0,2024-02-27 18:15:00,2024-02-27 18:16:00,0.016667

In [ ]:
event_type_categories = df_subset.groupby(['EVENT_TYPE'])[['EVENT_TYPE']].count()
event_type_categories

                    EVENT_TYPE
EVENT_TYPE
Heavy Rain                   1
TORNADO/WATERSPOUT           1
Thunderstorm Wind            3
Tornado                  56606

In [ ]:
df_tornados = df_subset[df_subset['EVENT_TYPE'] == 'Tornado']

In [ ]:
EF_scale_categories = df_tornados.groupby(['TOR_F_SCALE'])[['TOR_F_SCALE']].count()
EF_scale_categories

             TOR_F_SCALE
TOR_F_SCALE
EF0                12186
EF1                 9038
EF2                 2464
EF3                  662
EF4                  137
EF5                   14
EFU                 1378
F0                 16432
F1                  9386
F2                  3408
F3                  1124
F4                   348
F5                    29

In [ ]:
#df_tornados.replace({'TOR_F_SCALE' : { 'F0' : 'EF0',
                                     'F1' : 'EF1',
                                     'F2' : 'EF2',
                                     'F3' : 'EF3',
                                     'F4' : 'EF4',
                                     'F5' : 'EF5' }}, inplace = True)

<ipython-input-22-7bad60537f44>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tornados.replace({'TOR_F_SCALE' : { 'F0' : 'EF0',

In [ ]:
EF_scale_categories = df_tornados.groupby(['TOR_F_SCALE'])[['TOR_F_SCALE']].count()
EF_scale_categories

             TOR_F_SCALE
TOR_F_SCALE
EF0                28618
EF1                18424
EF2                 5872
EF3                 1786
EF4                  485
EF5                   43
EFU                 1378

In [ ]:
null_count = df_tornados.isnull().sum()
null_count

EPISODE_ID           15564
EVENT_ID                 0
STATE                    0
STATE_FIPS               0
EVENT_TYPE               0
CZ_TYPE                  0
CZ_FIPS                  0
CZ_NAME                  0
BEGIN_DATE_TIME          0
CZ_TIMEZONE              0
END_DATE_TIME            0
INJURIES_DIRECT          0
INJURIES_INDIRECT        0
DEATHS_DIRECT            0
DEATHS_INDIRECT          0
DAMAGE_PROPERTY          0
DAMAGE_CROPS             0
TOR_F_SCALE              0
TOR_LENGTH              28
TOR_WIDTH               28
EPISODE_NARRATIVE    24998
EVENT_NARRATIVE      17374
NET_DAMAGE               0
BEGIN                    0
END                      0
DURATION_HOURS           0
dtype: int64

In [ ]:
df_tornados[df_tornados['TOR_WIDTH'].isnull()]

,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,BEGIN_DATE_TIME,CZ_TIMEZONE,...,DAMAGE_CROPS,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,EPISODE_NARRATIVE,EVENT_NARRATIVE,NET_DAMAGE,BEGIN,END,DURATION_HOURS
1706239,2042485.0,5556963,OREGON,41.0,Tornado,C,1,BAKER,17-MAY-96 17:00:00,PST,...,0.0,EF0,NaN,NaN,A strong upper level disturbance produced stro...,NaN,0.0,1996-05-17 17:00:00,1996-05-17 18:00:00,1.00
1726576,2037726.0,5724959,OKLAHOMA,40.0,Tornado,Z,18,KINGFISHER,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1726957,2037726.0,5724983,OKLAHOMA,40.0,Tornado,Z,13,NOBLE,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1726959,2037726.0,5724987,OKLAHOMA,40.0,Tornado,Z,23,CADDO,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1727104,2037726.0,5724963,OKLAHOMA,40.0,Tornado,Z,19,LOGAN,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1729421,2037726.0,5724967,OKLAHOMA,40.0,Tornado,Z,20,PAYNE,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1729516,2037726.0,5724971,OKLAHOMA,40.0,Tornado,Z,25,OKLAHOMA,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1729518,2037726.0,5724975,OKLAHOMA,40.0,Tornado,Z,26,LINCOLN,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1729595,2037726.0,5725007,OKLAHOMA,40.0,Tornado,Z,31,SEMINOLE,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1729671,2037726.0,5725011,OKLAHOMA,40.0,Tornado,Z,32,HUGHES,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1730477,2037726.0,5725027,OKLAHOMA,40.0,Tornado,Z,41,MURRAY,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1730686,2037726.0,5724991,OKLAHOMA,40.0,Tornado,Z,27,GRADY,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1730815,2037726.0,5725003,OKLAHOMA,40.0,Tornado,Z,30,POTTAWATOMIE,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1731145,2037726.0,5724999,OKLAHOMA,40.0,Tornado,Z,29,CLEVELAND,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1731508,2037726.0,5724995,OKLAHOMA,40.0,Tornado,Z,28,MCCLAIN,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1731702,2037726.0,5724979,OKLAHOMA,40.0,Tornado,Z,12,GARFIELD,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1732859,2037726.0,5725023,OKLAHOMA,40.0,Tornado,Z,40,GARVIN,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1733252,2037726.0,5725055,OKLAHOMA,40.0,Tornado,Z,50,LOVE,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1733253,2037726.0,5725063,OKLAHOMA,40.0,Tornado,Z,39,STEPHENS,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1733374,2037726.0,5725051,OKLAHOMA,40.0,Tornado,Z,49,PUSHMATAHA,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1733375,2037726.0,5725059,OKLAHOMA,40.0,Tornado,Z,52,BRYAN,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1734266,2037726.0,5725035,OKLAHOMA,40.0,Tornado,Z,45,JEFFERSON,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1734347,2037726.0,5725031,OKLAHOMA,40.0,Tornado,Z,43,COAL,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1737218,2037726.0,5725015,OKLAHOMA,40.0,Tornado,Z,38,COMANCHE,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1737219,2037726.0,5725019,OKLAHOMA,40.0,Tornado,Z,53,CHOCTAW,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1739315,2037726.0,5725039,OKLAHOMA,40.0,Tornado,Z,46,CARTER,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1739317,2037726.0,5725043,OKLAHOMA,40.0,Tornado,Z,47,JOHNSTON,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25
1739431,2037726.0,5725047,OKLAHOMA,40.0,Tornado,Z,48,ATOKA,24-MAR-96 10:15:00,CST,...,0.0,EF0,NaN,NaN,Severe thunderstorms moved eastward across a l...,NaN,0.0,1996-03-24 10:15:00,1996-03-24 16:30:00,6.25

In [ ]:
df_tornados = df_tornados.drop(df_tornados[df_tornados['EPISODE_ID'] == 2037726.0].index)

In [ ]:
df_tornados = df_tornados.drop(['EPISODE_ID', 'EPISODE_NARRATIVE', 'EVENT_NARRATIVE'], axis=1)

In [ ]:
df_tornados = df_tornados.drop(['EVENT_TYPE', 'END_DATE_TIME', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'BEGIN', 'END'], axis=1)

In [ ]:
df_tornados.head()

,EVENT_ID,STATE,STATE_FIPS,CZ_TYPE,CZ_FIPS,CZ_NAME,BEGIN_DATE_TIME,CZ_TIMEZONE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,NET_DAMAGE,DURATION_HOURS
2,1184919,OKLAHOMA,40.0,C,39,CUSTER,19-MAY-24 18:39:00,CST-6,0,0,0,0,EF1,6.70,400.0,150000.0,0.383333
18,1216653,IOWA,19.0,C,51,DAVIS,05-NOV-24 11:01:00,CST-6,0,0,0,0,EF0,0.32,50.0,120000.0,0.016667
105,1155977,ILLINOIS,17.0,C,31,COOK,27-FEB-24 19:32:00,CST-6,0,0,0,0,EF1,2.58,110.0,0.0,0.050000
106,1155978,ILLINOIS,17.0,C,31,COOK,27-FEB-24 19:34:00,CST-6,0,0,0,0,EF1,2.45,160.0,0.0,0.050000
111,1155954,ILLINOIS,17.0,C,103,LEE,27-FEB-24 18:15:00,CST-6,0,0,0,0,EF0,0.05,10.0,0.0,0.016667

In [ ]:
df_tornados = df_tornados.drop(['STATE_FIPS', 'CZ_FIPS'], axis=1)

In [ ]:
df_encoded = pd.get_dummies(df_tornados, columns=['STATE', 'CZ_TYPE', 'CZ_NAME', 'CZ_TIMEZONE', 'TOR_F_SCALE'])

In [ ]:
df_encoded.head()

,EVENT_ID,BEGIN_DATE_TIME,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,TOR_LENGTH,TOR_WIDTH,NET_DAMAGE,DURATION_HOURS,...,CZ_TIMEZONE_PST,CZ_TIMEZONE_PST-8,CZ_TIMEZONE_UNK,TOR_F_SCALE_EF0,TOR_F_SCALE_EF1,TOR_F_SCALE_EF2,TOR_F_SCALE_EF3,TOR_F_SCALE_EF4,TOR_F_SCALE_EF5,TOR_F_SCALE_EFU
2,1184919,19-MAY-24 18:39:00,0,0,0,0,6.70,400.0,150000.0,0.383333,...,False,False,False,False,True,False,False,False,False,False
18,1216653,05-NOV-24 11:01:00,0,0,0,0,0.32,50.0,120000.0,0.016667,...,False,False,False,True,False,False,False,False,False,False
105,1155977,27-FEB-24 19:32:00,0,0,0,0,2.58,110.0,0.0,0.050000,...,False,False,False,False,True,False,False,False,False,False
106,1155978,27-FEB-24 19:34:00,0,0,0,0,2.45,160.0,0.0,0.050000,...,False,False,False,False,True,False,False,False,False,False
111,1155954,27-FEB-24 18:15:00,0,0,0,0,0.05,10.0,0.0,0.016667,...,False,False,False,True,False,False,False,False,False,False